CREATE USER 'SKRINInsertApp'@'localhost' IDENTIFIED BY '***';

GRANT SELECT ,
INSERT ,

UPDATE ,
TRIGGER,
EXECUTE ON * . * TO 'SKRINInsertApp'@'localhost' IDENTIFIED BY '***' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON `testshop` . * TO 'SKRINInsertApp'@'localhost';